---
version: "2"

services:
  ca_in_a_box:
    build:
      context: .
      dockerfile: Dockerfile
    image: ca-in-a-box:latest
    tmpfs:
      - /tmp
      - /root/ca
    volumes:
      - ./config/:/root/cfg
      - ./output/:/root/output
    environment:
    - AWS_REGION
    - AWS_ACCESS_KEY_ID
    - AWS_SECRET_ACCESS_KEY
    env_file:
      - ./config/config.txt
