---
version: "2"

services:
  ca_in_a_box:
    build:
      context: .
      dockerfile: Dockerfile
    image: ca-in-a-box:latest
    tmpfs:
      - /tmp
      - /root/ca
    volumes:
      - ./config/:/root/cfg
      - ./output/:/root/output
      - $HOME/.aws:/root/.aws:ro
    env_file:
      - ./config/config.txt
